### ISSUE TITLE
build and push docker image

### ISSUE THREAD

**Issue by dmd** [harvard-nrg/scanbuddy#19]
Could you please have GHA build and push a docker image?

Here is an example `.github/workflows/docker-push.yml` for you. You will need to set up your username and token in https://github.com/harvard-nrg/scanbuddy/settings/secrets/actions .

```yaml
name: Upload latest to DockerHub

on:
  workflow_dispatch:
  push:
    branches: [ main, ]

jobs:
  docker:

    runs-on: ubuntu-latest
    
    steps:
      - name: Login to DuckerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scanbuddy:latest
```
